= M3uParser

M3uParser provides Java API around an (extended) M3U playlist. Based on ANTLR grammar.

image:https://api.bintray.com/packages/krom/maven/m3uparser/images/download.svg["Download", link="https://bintray.com/krom/maven/m3uparser/_latestVersion"]
image:https://travis-ci.org/kromkrom/m3uparser.svg?branch=master["Build Status", link="https://travis-ci.org/kromkrom/m3uparser"]
image:https://api.codeclimate.com/v1/badges/7a0a58d5015b63a63dce/maintainability["Maintainability", link="https://codeclimate.com/github/kromkrom/m3uparser/maintainability"]

== Usage
Public API consists of: `DefaultM3uParser` which implements `M3uParserWrapper` and `PlaylistEntry`.

`getPlaylistProperties()` returns a map of properties from `#EXTM3U` section.

`getPlaylistEntries()` return a list of playlist entries, each represented by `PlaylistEntry` class.
Its members are:

* `title` -- an entry title,
* `path` -- a path or a URL of a file,
* `length` -- file length (commonly -1 or 0 for streams),
* `group` -- group name from `#EXTGRP` (could be `null`),
* `properties` -- a map of entry-specific properties from `#EXTINF` section.

== Format specification
There is no formal specification for M3U format (see https://en.wikipedia.org/wiki/M3U).

M3uParser supports "extended M3U", in particular `\#EXTM3U`, `#EXTINF` and `#EXTGRP` directives.
All other comments (starting with `#`) are ignored.